travis:
  secure:
    BINSTAR_TOKEN: VnSG7+EyelTxckLAGGNU+Z5VXdsojGOFkCJm5eJnhthbPnM3O1ws+kuMkqOhaEXKU0uNZSf37xwGB8deKsGlXlfeJ7gkfLpT6JHeyU+Ik2IzcUzf1IlLotFHRHtYrQI2LQYlVZ8jd0uMo7EG3apPkGs5aAZH2NVxJu2reHwJWeJlsGTDr120dKGJrxXeZIH3uTfd2gjnzFkpJPVJfBHn14Lcs08YWt6f7jZ+A2qUdeN3mVbk5cOBWUbGXrZFy3XS/ro7JfziZcZuu9N0+PU45nDQeJfBq9rJwyNpqxOK9ji8Q3NwIOYAbnkLBALmSk8U/q5CHqeE5l19k9/DPu49NfXgSOzJVL8dfkXz9tN393HZr5DFIq7afkghzp9N9dGQMmMKLdC8nJfFkTWq2TSyo9jSomvmyTPEOvO/KqRtUPej2DSfhQDkXH3QElWoQrryxurjZHqW7QSFwktNzqoouQ6VNQCxwrq3K6lH9YxIKh7cUjrZW2qI43Yu5MagP/5OvZ0bwtQTd/qZ9z0a3QlNh2cJyT6GdHyYC+aqEH30UF4ajD6xum8/gNThbgQjyr99hXAxEP0o/ijUXs+XL+Lvlwxvet4y3YPpYW1l2u5U2hXsiDTCjLdJIuWJNqv7kus4nu09Ugjq6pkXu5YJBwpw16/soa+VnbigxRKZE4U93oY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
